### ISSUE TITLE
Since the last Update Ownbackup generates about 10 Backups a day

### ISSUE THREAD

**Issue by Mannshoch** [pbek/ownbackup#9] opened 2017-01-09 22:24 UTC
Since the last Update Ownbackup generates about 10 Backups a day

How could I limit around one or two per week and maybe with automatic remove of old backups? The backup directory is flooded at moment.

**Comment by pbek** [comment] 2017-01-10 04:15
Nothing concerning the way backups are generated has changed for a long time. Hourly backups are kept for about 24 hours...

See: <https://github.com/pbek/ownbackup#features>

Does that answer your question?

**Comment by Mannshoch** [comment] 2017-01-10 07:47
At moment the ownbackup directory contain 164 directories beginning with the Day I updated Owncloud and OwnBackup at 22.12.2016. Since this Day I have 9. Directorys per Day. It seems that every 2h30min a directory was created. 

My shared Hoster has set-up cronjobs to triggering cron.php every 15min
Owncloud: 8.2.9 
OwnBackup: 16.11.0

**Comment by pbek** [comment] 2017-01-10 07:52
I'm sorry, I can't reproduce that under Nextcloud 10.
If you want to play around with the code, here is where the list of backups to remove is generated: <https://github.com/pbek/ownbackup/blob/develop/service/backupservice.php#L635>

**Comment by Mannshoch** [comment] 2017-01-10 11:18
Thanks for that. Sadly I have to say I do not now how to programming.

My workaround at moment is to remove it manually. My shared hoster told me to upgrade his system in Spring so I'm able to upgrade to Nextcloud then.

**Comment by pbek** [comment] 2017-01-14 21:09
I will close this issue until there is more information.

**Closed as completed** 2017-02-10 12:15 UTC
